### ISSUE TITLE
Some trial and error report on Windows

### ISSUE THREAD

**Issue by yoonsejong** [MTU-Tonic/vermouth#4]
Thanks for the nice challenge judge system. This is neither an issue nor a bug. Just some information for those who want to run it on Windows. Hope this helps.

# Compilation

Use [Maven](https://maven.apache.org/). Run 

```bash
mvn package
```

from the repo root. Your vermouth.jar will be created inside a directory called target.

# Source code change needed for Windows

For all the instructions, on Windows systems, use semicolon (;) for path delimiters instead of colons (:).

For Windows, due to filename and path convention, following lines need to be changed.

At line 159 of eaai.ginrummy.Main.java, change
```java
String identifier = cmd.getOptionValue("id", (new SimpleDateFormat("yyyy-MM-dd-HH:mm:ss:SSS")).format(new Date()));
```
into
```java
String osdepstr = "yyyy-MM-dd-HH:mm:ss:SSS";
if (System.getProperty("os.name").toLowerCase().indexOf("win") >= 0) {
	osdepstr = "yyyy-MM-dd_HH-mm-ss-SSS";
}
String identifier = cmd.getOptionValue("id", (new SimpleDateFormat(osdepstr)).format(new Date()));
```
At line 48 of eaai.ginrummy.util.FileMap.java, change
```java
Path path = Paths.get(String.format("./%s.zip", identifier)).toAbsolutePath().normalize();
URI uri = URI.create("jar:file:" + path);
```
into
```java
URI uri;
if (System.getProperty("os.name").toLowerCase().indexOf("win") >= 0) {
	uri = URI.create("jar:" + Paths.get(String.format("./%s.zip", identifier)).toUri());
} else {
	Path path = Paths.get(String.format("./%s.zip", identifier)).toAbsolutePath().normalize();
	uri = URI.create("jar:file:" + path);
}
```

# Run

I've noticed that blindly trying to use SimpleGinRummyPlayer.java may not be a good idea due to class definition not found exception you may encounter. Better to use import instead of package if you have just one file. For example:

```java
import ginrummy.*;
```

To run a simulation, Windows must use full absolute path to be properly recognized as an URL.

```bash
java -jar vermouth.jar --oneall --games 100 --agents "file://D:/vermouth-master/src/main/java/SimplePlayer" "file://D:/vermouth-master/src/main/java/SimplePlayer"
```

**Comment by JasonHiebel** [comment]
Thank you very much for this feedback (somehow I missed it until today)!

I intend for the tournament software to be useable out-of-the-box. Ideally, teams won't even need to recompile the tournament software code and instead can just download the code. So I will be incorporating your changes into the base code here and I'll add the windows-based documentation to the readme.
